apps/team/urls.py
from django.urls import path, include
from . import views

app_name = 'team'

urlpatterns = [
    path('myaccount/teams/add/', views.add, name='add'),
    path('activate_team/<int:team_id>/', views.activate_team, name='activate_team'),
    path('<int:team_id>/', views.team, name='team'),
    path('edit/', views.edit, name='edit'),
]

seigeKaiserreichTrak/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('', include('apps.userprofile.urls')),
    path('', include('apps.team.urls')),
    path('', include('apps.project.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/team/models.py
from django.contrib.auth.models import User
from django.db import models



class Team(models.Model):

    ACTIVE = 'active'
    DELETED = 'deleted'

    CHOICES_STATUS = (
        (ACTIVE, 'Active'),
        (DELETED, 'Deleted')
    )


    title = models.CharField(max_length=255)
    members = models.ManyToManyField(User, related_name='teams')
    created_by = models.ForeignKey(User, related_name='created_teams', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=ACTIVE)
    # plan = models.ForeignKey(Plan, related_name='teams', on_delete=models.CASCADE)
    # plan_end_date = models.DateTimeField(blank=True, null=True)
    # plan_status = models.CharField(max_length=20, choices=CHOICES_PLAN_STATUS, default=PLAN_ACTIVE)
    # stripe_customer_id = models.CharField(max_length=255, blank=True, null=True)
    # stripe_subscription_id = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        ordering = ['title']
    
    def __str__(self):
        return self.title

apps/team/views.py
import random
from .models import Team
from datetime import datetime
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404


@login_required
def team(request, team_id):
    team = get_object_or_404(Team, pk=team_id, status=Team.ACTIVE, members__in=[request.user])
    # invitations = team.invitations.filter(status=Invitation.INVITED)

    return render(request, 'team/team.html', {'team': team})


@login_required
def activate_team(request, team_id):
    team = get_object_or_404(Team, pk=team_id, status=Team.ACTIVE, members__in=[request.user])
    userprofile = request.user.userprofile
    userprofile.active_team_id = team.id
    userprofile.save()

    messages.info(request, 'The team was activated')
    return redirect('team:team', team_id=team.id)


@login_required
def add(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        
        if title:
            team = Team.objects.create(title=title, created_by=request.user)
            team.members.add(request.user)
            team.save()
            userprofile = request.user.userprofile
            userprofile.active_team_id = team.id
            userprofile.save()
            
            return redirect('myaccount')
    
    return render(request, 'team/add.html')


@login_required
def edit(request):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE, 
                                members__in=[request.user])

    if request.method == 'POST':
        title = request.POST.get('title')
        if title:
            team.title = title
            team.save()
            messages.info(request, 'The changes was saved')
            return redirect('team:team', team_id=team.id)
    return render(request, 'team/edit.html', {'team': team})

apps/team/templates/team/add.html
{% extends 'core/base.html' %}

{% block title %}Add team | {% endblock %}

{% block content %}
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li><a href="{% url 'myaccount' %}">My account</a></li>
            <li class="is-active"><a href="{% url 'team:add' %}" aria-current="page">Add team</a></li>
        </ul>
    </nav>

    <div class="columns" id="team-app">
        <div class="column is-4">
            <h1 class="title">Add team</h1>

            <form method="post" action="." @submit="validateForm">
                {% csrf_token %}

                <div class="field">
                    <label>Title</label>
                    <div class="control">
                        <input type="text" name="title" id="id_title" v-model="title">
                    </div>
                </div>

                <div class="notification is-danger" v-if="errors.length">
                    <p v-for="error in errors">[[ error ]]</p>
                </div>

                <div class="field">
                    <div class="control">
                        <button class="button is-success">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block scripts %}

<script>
    const TeamApp = {
        data() {
            return {
                title: '',
                errors: []
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            validateForm(e) {
                this.errors = []

                if (this.title) {
                    return true
                }
                e.preventDefault()
                this.errors.push('The title field is missing')
                return false
            }
        }
    }

    Vue.createApp(TeamApp).mount('#team-app')
</script>
{% endblock %}

apps/team/templates/team/edit.html
{% extends 'core/base.html' %}

{% block title %}Edit team | {% endblock %}

{% block content %}
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li><a href="{% url 'myaccount' %}">My account</a></li>
            <li class="is-active"><a href="{% url 'team:edit' %}" aria-current="page">Edit team</a></li>
        </ul>
    </nav>

    <div class="columns" id="team-app">
        <div class="column is-4">
            <h1 class="title">Edit team</h1>

            <form method="post" action="." @submit="validateForm">
                {% csrf_token %}

                <div class="field">
                    <label>Title</label>

                    <div class="control">
                        <input type="text" name="title" id="id_title" class="input" v-model="title">
                    </div>
                </div>

                <div class="notification is-danger" v-if="errors.length">
                    <p v-for="error in errors">[[ error ]]</p>
                </div>

                <div class="field">
                    <div class="control">
                        <button class="button is-success">Save changes</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block scripts %}
<script>
    const TeamApp = {
        data() {
            return {
                title: '{{ team.title }}',
                errors: []
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            validateForm(e) {
                this.errors = []

                if (this.title) {
                    return true
                }

                e.preventDefault()

                this.errors.push('The title field is missing')
                
                return false
            }
        }
    }

    Vue.createApp(TeamApp).mount('#team-app')
</script>
{% endblock %}

apps/team/templates/team/team.html
{% extends 'core/base.html' %}

{% block title %}{{ team.title }} | {% endblock %}

{% block content %}
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li><a href="{% url 'myaccount' %}">My account</a></li>
            <li class="is-active"><a href="{% url 'team:team' team.id %}" aria-current="page">{{ team.title }}</a></li>
        </ul>
    </nav>

    <div class="columns is-multiline" id="team-app">
        <div class="column is-4">
            <h1 class="title">{{ team.title }}</h1>

            <p><strong>Current plan: </strong>{{ team.plan.title }}</p>

            {% if team.plan.title != 'Free' %}
                <p><strong>Plan end date: </strong>{{ team.plan_end_date|date:"Y-m-d" }}{% if team.plan_status == 'active' %} (auto renewing){% endif %}</p>
            {% endif %}

            {% if request.user == team.created_by %}
                <a href="#" class="button is-primary">Invite users</a>
                <a href="#" class="button is-success">Change plan</a>
            {% endif %}

            <hr>

            <h2 class="subtitle mt-6">Members</h2>

            {% for member in team.members.all %}
                <p>{{ member.username }}</p>
            {% endfor %}

            <h2 class="subtitle mt-6">Invitated members</h2>

            {% for member in invitations %}
                <p>{{ member.email }} - {{ member.date_sent|timesince }} ago</p>
            {% endfor %}
        </div>

        {% if team.created_by == request.user %}
            <div class="column is-12">
                <hr>
        
                <h3 class="subtitle">Owner actions</h3>

                <a href="{% url 'team:edit' %}" class="button is-warning">Edit team</a>
            </div>
        {% endif %}
    </div>
{% endblock %}