apps/core/urls.py
from django.urls import path, include
from . import views

apps = 'apps.core'

urlpatterns = [
    path('', views.frontpage, name='frontpage'),
    path('privacy/', views.privacy, name='privacy'),
    path('terms/', views.terms, name='terms'),
    path('plans/', views.plans, name='plans'),
    path('signup/', views.signup, name='signup'),
]

apps/project/urls.py
from django.urls import path
from . import views

app_name = 'project'


urlpatterns = [
    path('projects/', views.projects, name='projects'),
    path('<int:project_id>/', views.project, name='project'),
]

seigeKaiserreichTrak/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('', include('apps.userprofile.urls')),
    path('', include('apps.team.urls')),
    path('', include('apps.project.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/core/models.py
from django.db import models

apps/core/views.py
from django.shortcuts import render
from apps.userprofile.models import Userprofile
from django.contrib.auth import login
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm


def frontpage(request):
    return render(request, 'core/frontpage.html')

def privacy(request):
    return render(request, 'core/privacy.html')

def terms(request):
    return render(request, 'core/terms.html')

def plans(request):
    return render(request, 'core/plans.html')


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        
        if form.is_valid():
            user = form.save()
            user.email = user.username
            user.save()
            userprofile = Userprofile.objects.create(user=user)
            login(request, user)
            return redirect('frontpage')
    else:
        form = UserCreationForm()
        
    return render(request, 'core/signup.html', {'form':form})

apps/core/templates/core/base.html
<!DOCTYPE html>

<html>
    <head>
        <!-- Meta -->
        <meta charset="utf-8">
        <!-- Title -->
        <title>{% block title %} {% endblock %}Minutos</title>
        <!-- CSS files -->
        <link rel="stylesheet" type="text/css" href="https://cdn.delivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    </head>


    <body>
        <!-- Navbar -->
        <div id="navbar-app">
            <nav class="navbar{% if request.user.is_authenticated %} is-dark{% else %} is-light{% endif %}">
                <div class="navbar-brand">
                    <a href="/" class="navbar-item"><strong>Kitos</strong></a>
                </div>

                <div class="navbar-menu">
                    <div class="navbar-end">
                        {% if not request.user.is_authenticated %}
                            <a href="{% url 'plans' %}" class="navbar-item">Plans</a>
                        {% else %}
                            <a href="#" class="navbar-item">Dashboard</a>
                            <a href="{% url 'project:projects' %}" class="navbar-item">Projects</a>
                            <div class="navbar-item" v-if="!trackingTime">
                                <div class="buttons">
                                    <a class="button is-success" @click="startTimer()">
                                        <span class="icon"><i class="fas fa-stopwatch"></i></span>
                                        <span>Start</span>
                                    </a>
                                </div>
                            </div>

                            <div class="navbar-item" v-else>
                                <div class="buttons">
                                    <a class="button is-warning" @click="stopTimer()">
                                        <span class="icon"><i class="fas fa-stopwatch"></i></span>
                                        <span>[[ readableSeconds ]] (stop)</span>
                                    </a>
                                </div>
                            </div>
                        {% endif %}
                        
                        <div class="navbar-item">
                            <div class="buttons">
                                {% if request.user.is_authenticated %}
                                    <a href="#" class="button is-success">
                                        <span class="icon"><i class="fas fa-user"></i></span>
                                        <span>
                                            {% firstof request.user.get_full_name request.user.username %}{% if active_team %} ({{ active_team.title }}){% endif %}
                                        </span>
                                    </a>
                                {% else %}
                                    <a href="{% url 'signup' %}" class="button is-success"><strong>Sign up</strong></a>
                                    <a href="{% url 'login' %}" class="button">Log in</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </nav>

            <div class="modal" :class="{'is-active': showTrackingModal}">
                <div class="modal-background"></div>

                <div class="modal-card">
                    <div class="modal-card-head">
                        <p class="modal-card-title">Tracked time</p>
                    </div>

                    <div class="modal-card-body">
                        <p>You have tracked [[ readableSeconds ]]</p>
                    </div>

                    <footer class="modal-card-foot">
                        <button class="button is-primary" @click="addToTask()">Add to task</button>
                        <button class="button is-success" @click="addLater()">Add later</button>
                        <button class="button is-danger" @click="discardTimer()">Discard</button>
                    </footer>
                </div>
            </div>
        </div>
        <!-- End Navbar -->

        <!-- Main -->
        <section class="section">
            {% if messages %}
                {% for message in messages %}
                    <div class="notification is-info">{{ message }}</div>
                {% endfor %}
            {% endif %}

            {% block content %}
            {% endblock %}
        </section>
        <!-- End Main -->

        <!-- Footer -->
        <footer class="footer">
            <div class="columns is-multiline">
                <div class="column is-4">
                    <h2 class="subtitle">Minutos</h2>
                </div>

                <div class="column is-offset-6 is-2">
                    <ul>
                        <li><a href="#">Contact</a></li>
                        <li><a href="{% url 'privacy' %}">Privacy policy</a></li>
                        <li><a href="{% url 'terms' %}">Terms of service</a></li>
                    </ul>
                </div>

                <div class="column is-12 has-text-centered">
                    <p><strong>Copyright (c)</strong> 2024</p>
                </div>
            </div>
        </footer>
        <!-- End Footer -->

        <!-- Scripts -->
        <script src="https://use.fontawesome.com/releases/v5.14.0/js/all.js"></script>
        <script src="https://unpkg.com/vue@next"></script>
        <script>
            var NavbarApp = {
                data() {
                    return {
                        seconds: {{ active_entry_seconds }},
                        trackingTime: false,
                        showTrackingModal: false,
                        timer: null,
                        entryID: 0,
                        startTime: '{{ start_time }}'
                    }
                },
                delimiters: ['[[', ']]'],
                methods: {
                    startTimer() {
                        fetch('/dashboard/projects/api/start_timer/', {
                            method: 'POST',
                            headers: {
                                'Content-Type': 'application/json',
                                'X-CSRFToken': '{{ csrf_token }}'
                            }
                        })
                        .then((response) => {
                            return response.json()
                        })
                        .then((result) => {
                            this.startTime = new Date()
                            this.trackingTime = true

                            this.timer = setInterval(() => {
                                this.seconds = (new Date() - this.startTime) / 1000
                            }, 1000)
                        })
                    },
                    stopTimer() {
                        fetch('/dashboard/projects/api/stop_timer/', {
                            method: 'POST',
                            headers: {
                                'Content-Type': 'application/json',
                                'X-CSRFToken': '{{ csrf_token }}'
                            }
                        })
                        .then((response) => {
                            return response.json()
                        })
                        .then((result) => {
                            this.entryID = result.entryID
                            this.showTrackingModal = true
                            this.trackingTime = false

                            window.clearTimeout(this.timer)
                        })
                    },
                    discardTimer() {
                        fetch('/dashboard/projects/api/discard_timer/', {
                            method: 'POST',
                            headers: {
                                'Content-Type': 'application/json',
                                'X-CSRFToken': '{{ csrf_token }}'
                            }
                        })
                        .then((response) => {
                            this.seconds = 0
                            this.showTrackingModal = false
                        })
                    },
                    addLater() {
                        this.seconds = 0
                        this.showTrackingModal = false
                    },
                    addToTask() {
                        console.log('addToTask')
                        window.location.href = '/dashboard/projects/track_entry/' + this.entryID + '/'
                    }
                },
                mounted() {
                    if (this.seconds !== 0) {
                        this.trackingTime = true
                        this.timer = setInterval(() => {
                            this.seconds = (new Date() - new Date(this.startTime)) / 1000
                        }, 1000)
                    }
                },
                computed: {
                    readableSeconds() {
                        const d = Number(this.seconds);
                        const h = Math.floor(d / 3600);
                        const m = Math.floor(d % 3600 / 60);
                        const s = Math.floor(d % 3600 % 60);

                        const hDisplay = h > 0 ? h + (h == 1 ? "h, " : "h, ") : "";
                        const mDisplay = m > 0 ? m + (m == 1 ? "m, " : "m, ") : "";
                        const sDisplay = s >= 0 ? s + (s == 1 ? "s" : "s") : "";

                        return hDisplay + mDisplay + sDisplay; 
                    }
                }
            }

            Vue.createApp(NavbarApp).mount('#navbar-app')
        </script>
        {% block scripts %}
        {% endblock %}
        <!-- End Scripts -->
    </body>
</html>

apps/core/templates/core/frontpage.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Home | {% endblock %}

{% block content %}

<section class="hero is-medium is-light is-bold">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">Welcome to Pilot</h1>
            <h2 class="subtitle">Manage your project time with tracking made simple by Pilot-Minutos</h2>
        </div>
    </div>
</section>

<div class="container">
    <div class="columns">
        <div class="column is-8 is-offset-2">
            <div class="columns is-align-items mt-6">
                <div class="column is-4 image">
                    <img src="{% static 'images/features-tracktime.jpg' %}">
                </div>

                <div class="column is-8 text">
                    <h2 class="subtitle">Manage and Trak projects</h2>
                    <p>Time tracking made simple. Enhance and Track Daily Activities of your Team to stay 
                        On time Deliveries to Clients.
                    </p>
                </div>
            </div>

            <div class="columns is-align-items mt-6">
                <div class="column is-8 text">
                    <h2 class="subtitle">Build Your team</h2>
                    <p>Manage and Work with Team to develope impossible Achievements to stay forward from the competion.</p>
                </div>

                <div class="column is-4 image">
                    <img src="{% static 'images/features-team.jpg' %}">
                </div>
            </div>

            <div class="columns is-align-items mt-6">
                <div class="column is-4 image">
                    <img src="{% static 'images/features-happyboss.jpg' %}">
                </div>

                <div class="column is-8 text">
                    <h2 class="subtitle">Team Manager</h2>

                    <p>Manager or Architect get all details of Projects.
                        Strive the impossibilities.
                    </p>
                </div>
            </div>
        </div>
    </div>

    <div class="columns is-align-items-center mt-6">
        <div class="column is-4 is-offset-4 has-text-centered">
            <h2 class="subtitle">Let's get started</h2>

            <a href="{% url 'signup' %}" class="button is-success is-large">Get a free account</a>
        </div>
    </div>
</div>
{% endblock %}

apps/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in | {% endblock %}

{% block content %}
    <section class="hero is-medium is-light is-bold">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">Log in</h1>
                <h2 class="subtitle">Log in to your account and start tracking time</h2>
            </div>
        </div>
    </section>  

    <div class="columns" id="signup-app">
        <div class="column is-6 is-offset-3">
            <form method="post" action="." class="mt-6">
                {% csrf_token %}

                {% if form.errors %}
                    <div class="notification is-danger">
                        {{ form.non_field_errors }}

                        {% for field in form %}
                            {% if field.errors %}{{ field.label }}: {{ field.errors|striptags }}{% endif %}
                        {% endfor %}
                    </div>
                {% endif %}

                <div class="field">
                    <label>E-mail</label>

                    <div class="control">
                        <input type="email" name="username" id="id_username" class="input">
                    </div>
                </div>

                <div class="field">
                    <label>Password</label>

                    <div class="control">
                        <input type="password" name="password" id="id_password" class="input">
                    </div>
                </div>

                <div class="field">
                    <div class="control">
                        <button class="button is-success">Log in</button>
                    </div>
                </div>
            </form>

            <hr>

            <h2 class="subtitle">Don't have an account?</h2>

            <a href="{% url 'signup' %}">Create one for free</a>
        </div>
    </div>
{% endblock %}

apps/core/templates/core/plans.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Plans | {% endblock %}

{% block content %}

        <section class="hero is-medium is-light is-bold">
            <div class="hero-body">
                <div class="container">
                    <h1 class="title">Plans</h1>
                    <h2 class="subtitle">Find the most suitable plan for your Team !
                    </h2>
                </div>
            </div>
        </section>


        <div class="columns mt-6">
            <div class="column is-3">
                <div class="card">
                    <div class="card-content">
                        <div class="media">
                            <div class="media-content">
                                <p class="title is-4">Free</p>
                                <p class="subtitle is-6">$0</p>
                            </div>
                        </div>
    
                        <div class="content">
                            <ul>
                                <li>3 projects</li>
                                <li>1 member</li>
                                <li>10 tasks per project</li>
                            </ul>
    
                            <hr>
    
                            <a href="#" class="button is-primary">Get started</a>
                        </div>
                    </div>
                </div>
            </div>
    
            <div class="column is-3">
                <div class="card">
                    <div class="card-content">
                        <div class="media">
                            <div class="media-content">
                                <p class="title is-4">Basic</p>
                                <p class="subtitle is-6">$5</p>
                            </div>
                        </div>
    
                        <div class="content">
                            <ul>
                                <li>10 projects</li>
                                <li>15 member</li>
                                <li>30 tasks per project</li>
                            </ul>
    
                            <hr>
    
                            <a href="#" class="button is-primary">Get started</a>
                        </div>
                    </div>
                </div>
            </div>
    
            <div class="column is-3">
                <div class="card">
                    <div class="card-content">
                        <div class="media">
                            <div class="media-content">
                                <p class="title is-4">Pro</p>
                                <p class="subtitle is-6">$10</p>
                            </div>
                        </div>
    
                        <div class="content">
                            <ul>
                                <li>25 projects</li>
                                <li>50 member</li>
                                <li>100 tasks per project</li>
                            </ul>
    
                            <hr>
    
                            <a href="#" class="button is-primary">Get started</a>
                        </div>
                    </div>
                </div>
            </div>
    
            <div class="column is-3">
                <div class="card">
                    <div class="card-content">
                        <div class="media">
                            <div class="media-content">
                                <p class="title is-4">Need more?</p>
                                <p class="subtitle is-6">$?</p>
                            </div>
                        </div>
    
                        <div class="content">
                            <ul>
                                <li>Need more projects?</li>
                                <li>Need more members?</li>
                                <li>Need more tasks?</li>
                            </ul>
    
                            <hr>
    
                            <a href="#" class="button is-primary">Contact us</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>


{% endblock %}

apps/core/templates/core/privacy.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Privacy policy | {% endblock %}

{% block content %}


<section class="hero is-medium is-light is-bold">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">Privacy policy</h1>
            <h2 class="subtitle">PilotTrak does not collect or share personal information. This is our policy
                in a nutshell.
            </h2>
        </div>
    </div>
</section>


{% endblock %}

apps/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up | {% endblock %}

{% block content %}
    <section class="hero is-medium is-light is-bold">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">Sign up</h1>
                <h2 class="subtitle">Get a free account and start tracking time</h2>
            </div>
        </div>
    </section>  

    <div class="columns" id="signup-app">
        <div class="column is-6 is-offset-3">
            <form method="post" action="." class="mt-6" v-on:submit="validateForm" novalidate>
                {% csrf_token %}

                {% if form.errors %}
                    <div class="notification is-danger">
                        {{ form.non_field_errors }}

                        {% for field in form %}
                            {% if field.errors %}{{ field.label }}: {{ field.errors|striptags }}{% endif %}
                        {% endfor %}
                    </div>
                {% endif %}

                <div class="notification is-danger" v-if="errors.length">
                    <p v-for="error in errors">
                        [[ error ]]
                    </p>
                </div>

                <div class="field">
                    <label>E-mail</label>

                    <div class="control">
                        <input type="email" name="username" id="id_username" class="input" v-model="username">
                    </div>
                </div>

                <div class="field">
                    <label>Password</label>

                    <div class="control">
                        <input type="password" name="password1" id="id_password1" class="input" v-model="password1">
                    </div>
                </div>

                <div class="field">
                    <label>Repeat password</label>

                    <div class="control">
                        <input type="password" name="password2" id="id_password2" class="input" v-model="password2">
                    </div>
                </div>

                <ul class="password-helt-text">
                    <li v-if="password1.length < 8">Your password must contain at least 8 characters</li>
                    <li v-if="!isNaN(password1)">Your password can't be entirely numeric.</li>
                </ul>

                <div class="field">
                    <div class="control">
                        <button class="button is-success">Sign up</button>
                    </div>
                </div>
            </form>

            <hr>

            <h2 class="subtitle">Already have an account?</h2>

            <a href="{% url 'login' %}">Click here to log in</a>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        const SignupApp = {
            data() {
                return {
                    username: '',
                    password1: '',
                    password2: '',
                    errors: []
                }
            },
            delimiters: ['[[', ']]'],
            methods: {
                validateForm(e) {
                    this.errors = []

                    if (!this.validateEmail(this.username)) {
                        this.errors.push('Your e-mail address in not valid!')
                    }

                    if (this.password1 === '') {
                        this.errors.push('Your password is missing')
                    }

                    if (this.password1.length < 8) {
                        this.errors.push('Your password must be at least 8 characters')
                    }

                    if (!isNaN(this.password1)) {
                        this.errors.push('Your password can\'t be enterily numeric')
                    }

                    if (this.password1 !== this.password2) {
                        this.errors.push('Your passwords does not match!')
                    }

                    if (this.errors.length) {
                        e.preventDefault()

                        return false
                    } else {
                        return true
                    }
                },
                validateEmail(email) {
                    if (/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/.test(email)) {
                        return true
                    }

                    return false
                }
            }
        }

        Vue.createApp(SignupApp).mount('#signup-app')
    </script>
{% endblock %}

apps/core/templates/core/terms.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Terms of service | {% endblock %}

{% block content %}


    <section class="hero is-medium is-light is-bold">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">Terms of service</h1>
                <h2 class="subtitle">Terms of service.</h2>
                <p>
                    Please check the Official Docs to know about Terms of Service.
                    Thank You !
                </p>
            </div>
        </div>
    </section>


{% endblock %}